import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>sim0wn</h1>
        </header>
        {children}
        <footer>
          <a
            href="https://www.linkedin.com/in/halissoncruz/"
            className="bi bi-linkedin social-media"
          ></a>
        </footer>
      </body>
    </html>
  );
}
